name: Build and push backend (dev)

on:
  push:
    branches: ["dev"]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # robinjorgensen
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: robinjorgensen/js24-server
          tags: |
            type=raw,value=dev
            type=raw,value=dev-${{ github.sha }}

      - name: Build and push (dev)
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=robinjorgensen/js24-server:buildcache
          cache-to: type=registry,ref=robinjorgensen/js24-server:buildcache,mode=max
